name = "sga-calendar"
compatibility_date = "2026-07-18"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "sga-calendar-db"
database_id = "c6cdc20c-4729-4781-8745-8a0eccb5351c"
